name: Serverless CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Serverless framework
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: serverless

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Serverless Framework
      run: npm install -g serverless

    - name: Install dependencies
      run: npm install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1

    - name: Deploy to Serverless
      env:
        STAGE: ${{ github.ref == 'refs/heads/main' && 'main' || 'dev' }}
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      run: serverless deploy --stage $STAGE